rosbridge_websocket:
  ros__parameters:
      authenticate: false
      port: 9000
      address: ""
      retry_startup_delay: 5
      fragment_timeout: 600
      delay_between_messages: 0
      max_message_size: "None"
      unregister_timeout: 10
      use_compression: false
      topics_glob: "''[*]''"
      services_glob: "''[*]''"
      params_glob: "''[*]''"
      bson_only_mode: false
